[build]
  command = "yarn rw db up --no-db-client --auto-approve && yarn rw build"
  publish = "web/dist"
  functions = "api/dist/functions"

[context.production]
[context.production.environment]
  AUTH0_DOMAIN=""
  AUTH0_CLIENT_ID=""
  AUTH0_AUDIENCE=""
  AUTH0_REDIRECT_URI=""

[dev]
  command = "yarn rw dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = 'netlify-plugin-prisma-provider'
  [plugins.inputs]
  path = 'api/prisma/schema.prisma'
